version: "3.9"
services:
  web:
    build: ./
    pull_policy: build
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80
      - 443
    volumes:
      - ./var/lib/docker/volumes/lion_website:/usr/share/nginx/html
      #- website:/usr/share/nginx/html

volumes:
  website:
