version: "3.9"
services:
  web:
    build: ./
    pull_policy: build
    image: biati-astrojs:2
    restart: unless-stopped
    ports:
      - 80
      - 443
    volumes:
      - website:/usr/share/nginx/html

volumes:
  website:
