version: "3.7"
services:
  site:
    image: nginx:alpine
    #pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080
    volumes:
      - website:/usr/share/nginx/html

volumes:
  website:
