version: "3.9"
services:
  site:
    image: node:lts-bullseye-slim
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: missing
    ports:
      - 8080:3000
    volumes:
      - site:./

volumes:
  site:
