version: "3.7"
services:
  site:
    image: joseluisq/static-web-server
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: build
    ports:
      - 3000
    volumes:
      - website:/public_html
    environment:
      - SERVER_ROOT=public_html
      - SERVER_COMPRESSION=true
      - SERVER_IGNORE_HIDDEN_FILES=true
      - SERVER_ERROR_PAGE_404=./website/404.html

volumes:
  website:
